apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: {{KUBEADM_CONTROL_PLANE_IP}}:6443
    token: {{BOOTSTRAP_TOKEN}}
    unsafeSkipCAVerification: true
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  name: {{HOSTNAME_OVERRIDE}}
  kubeletExtraArgs:
  - name: feature-gates
    value: {{FEATURE_GATES}}
  - name: cloud-provider
    value: {{EXTERNAL_CLOUD_PROVIDER}}
  - name: provider-id
    value: {{PROVIDER_ID}}
  - name: node-ip
    value: {{NODE_IP}}
  - name: hostname-override
    value: {{HOSTNAME_OVERRIDE}}
  - name: image-credential-provider-bin-dir
    value: /usr/local/bin
  - name: image-credential-provider-config
    value: /etc/kubernetes/credential-provider.yaml
  - name: resolv-conf
    value: /run/systemd/resolve/resolv.conf
  - name: system-cgroups
    value: /system.slice
  - name: runtime-cgroups
    value: /runtime.slice
  - name: kubelet-cgroups
    value: /runtime.slice
  - name: cgroup-root
    value: /
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failCgroupV1: false
