name: 'Update Dependencies'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

env:
  GOPROXY: https://proxy.golang.org

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    if: ${{ github.repository == 'kubernetes-sigs/provider-aws-test-infra' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout provider-aws-test-infra
        uses: actions/checkout@v3
        with:
          path: src/sigs.k8s.io/provider-aws-test-infra
      - name: Checkout Kubernetes
        uses: actions/checkout@v3
        with:
          repository: kubernetes/kubernetes
          path: src/k8s.io/kubernetes
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: '1.20.5'
      - name: Update Dependencies
        id: update_deps
        run: |
          hack/bump-k8s.sh
          echo 'changes<<EOF' >> $GITHUB_OUTPUT
          git status --porcelain >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        working-directory: src/sigs.k8s.io/provider-aws-test-infra
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          title: 'Update dependencies'
          commit-message: Update Kubernetes to latest master
          committer: github-actions <actions@github.com>
          author: github-actions <actions@github.com>
          branch: dependencies/update
          branch-suffix: timestamp
          base: master
          delete-branch: true
          labels: ok-to-test
          body: |
            Updating go.mod with latest kubernetes related dependencies...
        path: src/sigs.k8s.io/provider-aws-test-infra